call gofsh samples -o gofsh
cd gofsh\input\fsh\instances
rem samples\example01.fsh (Patient/GOFSH-GENERATED-ID-0)
ren GOFSH-GENERATED-ID-0.fsh example01.fsh
rem samples\example02.fsh (PractitionerRole/GOFSH-GENERATED-ID-1)
ren GOFSH-GENERATED-ID-1.fsh example02.fsh
rem samples\example03.fsh (Organization/GOFSH-GENERATED-ID-2)
ren GOFSH-GENERATED-ID-2.fsh example03.fsh
rem samples\example04.fsh (Practitioner/GOFSH-GENERATED-ID-3)
ren GOFSH-GENERATED-ID-3.fsh example04.fsh
rem samples\example05.fsh (Coverage/GOFSH-GENERATED-ID-4)
ren GOFSH-GENERATED-ID-4.fsh example05.fsh
rem samples\example06.fsh (Organization/GOFSH-GENERATED-ID-5)
ren GOFSH-GENERATED-ID-5.fsh example06.fsh
rem samples\example07.fsh (Encounter/GOFSH-GENERATED-ID-6)
ren GOFSH-GENERATED-ID-6.fsh example07.fsh
rem samples\example08.fsh (Observation/GOFSH-GENERATED-ID-7)
ren GOFSH-GENERATED-ID-7.fsh example08.fsh
rem samples\example09-1.fsh (Observation/GOFSH-GENERATED-ID-8)
ren GOFSH-GENERATED-ID-8.fsh example09-1.fsh
rem samples\example09-2.fsh (Observation/GOFSH-GENERATED-ID-9)
ren GOFSH-GENERATED-ID-9.fsh example09-2.fsh
rem samples\example09-3.fsh (Observation/GOFSH-GENERATED-ID-10)
ren GOFSH-GENERATED-ID-10.fsh example09-3.fsh
rem samples\example09-4.fsh (Specimen/GOFSH-GENERATED-ID-11)
ren GOFSH-GENERATED-ID-11.fsh example09-4.fsh
rem samples\example09.fsh (Observation/GOFSH-GENERATED-ID-12)
ren GOFSH-GENERATED-ID-12.fsh example09.fsh
rem samples\example10.fsh (Observation/GOFSH-GENERATED-ID-13)
ren GOFSH-GENERATED-ID-13.fsh example10.fsh
rem samples\example11.fsh (Observation/GOFSH-GENERATED-ID-14)
ren GOFSH-GENERATED-ID-14.fsh example11.fsh
rem samples\example12.fsh (Observation/GOFSH-GENERATED-ID-15)
ren GOFSH-GENERATED-ID-15.fsh example12.fsh
rem samples\example13.fsh (Observation/GOFSH-GENERATED-ID-16)
ren GOFSH-GENERATED-ID-16.fsh example13.fsh
rem samples\example14-1.fsh (Media/GOFSH-GENERATED-ID-17)
ren GOFSH-GENERATED-ID-17.fsh example14-1.fsh
rem samples\example14.fsh (Observation/GOFSH-GENERATED-ID-18)
ren GOFSH-GENERATED-ID-18.fsh example14.fsh
rem samples\example15.fsh (DocumentReference/GOFSH-GENERATED-ID-19)
ren GOFSH-GENERATED-ID-19.fsh example15.fsh
rem samples\example16.fsh (DiagnosticReport/GOFSH-GENERATED-ID-20)
ren GOFSH-GENERATED-ID-20.fsh example16.fsh
rem samples\example17.fsh (Bundle/GOFSH-GENERATED-ID-21)
ren GOFSH-GENERATED-ID-21.fsh example17.fsh
rem samples\example18.fsh (Bundle/GOFSH-GENERATED-ID-22)
ren GOFSH-GENERATED-ID-22.fsh example18.fsh
rem samples\example19.fsh (Bundle/GOFSH-GENERATED-ID-23)
ren GOFSH-GENERATED-ID-23.fsh example19.fsh
rem samples\example20.fsh (Bundle/GOFSH-GENERATED-ID-24)
ren GOFSH-GENERATED-ID-24.fsh example20.fsh
rem samples\example21.fsh (Bundle/GOFSH-GENERATED-ID-25)
ren GOFSH-GENERATED-ID-25.fsh example21.fsh
rem samples\example22.fsh (Bundle/GOFSH-GENERATED-ID-26)
ren GOFSH-GENERATED-ID-26.fsh example22.fsh
rem samples\example23.fsh (Bundle/GOFSH-GENERATED-ID-27)
ren GOFSH-GENERATED-ID-27.fsh example23.fsh
rem samples\example24.fsh (Bundle/GOFSH-GENERATED-ID-28)
ren GOFSH-GENERATED-ID-28.fsh example24.fsh
rem samples\example25.fsh (Bundle/GOFSH-GENERATED-ID-29)
ren GOFSH-GENERATED-ID-29.fsh example25.fsh
cd ..\..\..\..
