#define	$$urn   urn:oid:1.2.392.100495.100.
#define	$$url   http://jpfhir/eMunicipalCheckup/ValueSet/valueSet

//----------
#define	$$KN    乳がん検診
#define	$$item	過去の受診歴
#define	$$oidnum	2000
#define	$$cd$$KN_$$item	9P520000000000011
#define	$$cs$$KN_$$item	$$urn.$$oidnum
#define	$$cd$$KN_$$item	$$url-$$oidnum

#define	$$item	がんに係る症状の有無
#define	$$oidnum	2052
#define	$$cd$$KN_$$item	9P521000000000011
#define	$$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	マンモグラフィー検査判定
#define	$$cd$$KN_$$item	9N281000000000011
#define	$$oidnum	2200
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	マンモグラフィー検査所見
#define	$$cd$$KN_$$item	9N281160800000049

#define	$$item	精密検査対象有無 
#define	$$cd$$KN_$$item	9P522000000000011
#define	$$oidnum	2240
#define	$$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	その他所見
#define	$$cd$$KN_$$item	9P523160800000049

#define	$$item	偶発症の有無
#define	$$cd$$KN_$$item	9P524000000000011
#define	$$oidnum	2010
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P525000000000011
#define	$$oidnum	2250
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P526160800000049

#define	$$item	精密検査による偶発症の有無
#define	$$cd$$KN_$$item	9P527000000000011
#define	$$oidnum	2011
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

//----------
#define	$$KN  胃がん検診
#define	$$item	過去の受診歴
#define	$$cd$$KN_$$item	9P540000000000011
#define	$$oidnum	2000
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	がんに係る症状の有無
#define	$$cd$$KN_$$item	9P541000000000011
#define	$$oidnum	2052
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	胃部エックス線検査検査判定
#define	$$cd$$KN_$$item	9P542160700000011
#define	$$oidnum	2050
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	胃部エックス線検査所見
#define	$$cd$$KN_$$item	9P543160800000049

#define	$$item	胃内視鏡検査検査判定
#define	$$cd$$KN_$$item	9P544160700000011
#define	$$oidnum	2050
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	胃内視鏡検査所見
#define	$$cd$$KN_$$item	9P545160800000049

#define	$$item	精密検査の対象有無
#define	$$cd$$KN_$$item	9P546000000000011
#define	$$oidnum	2340
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	その他所見
#define	$$cd$$KN_$$item	9P547160800000049

#define	$$item	偶発症の有無
#define	$$item	$$item
#define	$$cd$$KN_$$item	9P548000000000011
#define	$$oidnum	2010
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P549000000000011
#define	$$oidnum	2350

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P550160800000049
#define	$$item	精密検査による偶発症の有無
#define	$$cd$$KN_$$item	9P551000000000011
#define	$$oidnum	2011
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

//--------
#define	$$KN  子宮頸がん検診
#define	$$item	過去の受診歴
#define	$$cd$$KN_$$item	9P560000000000011
#define	$$oidnum	2000
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	がんに係る症状の有無
#define	$$cd$$KN_$$item	9P561000000000011
#define	$$oidnum	2052
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	視診所見有無
#define	$$cd$$KN_$$item	9N291160700000011
#define	$$oidnum	2050
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	視診所見内容
#define	$$cd$$KN_$$item	9N291160800000049

#define	$$item	内診所見有無
#define	$$cd$$KN_$$item	9N296160700000011
#define	$$oidnum	2050
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	内診所見内容
#define	$$cd$$KN_$$item	9N296160800000049

#define	$$item	頸部細胞診検査判定
#define	$$cd$$KN_$$item	7A021000008543311
#define	$$oidnum	2400
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	頸部細胞診検査所見
#define	$$cd$$KN_$$item	7A021160808543349

#define	$$item	精密検査の対象有無
#define	$$cd$$KN_$$item	9P562000000000011
#define	$$oidnum	2440

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	その他所見
#define	$$cd$$KN_$$item	9P563160800000049
#define	$$item	偶発症の有無
#define	$$cd$$KN_$$item	9P564000000000011
#define	$$oidnum	2010
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P565000000000011
#define	$$oidnum	2450

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P566160800000049
#define	$$item	精密検査による偶発症の有無
#define	$$cd$$KN_$$item	9P567000000000011
#define	$$oidnum	2011
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$KN  大腸がん検診
#define	$$item	過去の受診歴
#define	$$cd$$KN_$$item	9P580000000000011
#define	$$oidnum	2000
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	大腸がんに係る症状の有無
#define	$$cd$$KN_$$item	9P581000000000011
#define	$$oidnum	2052
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	便潜血検査判定
#define	$$cd$$KN_$$item	1B040000001599811
#define	$$oidnum	2500
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	便潜血検査所見
#define	$$cd$$KN_$$item	1B040160801599849
#define	$$item	精密検査の対象有無
#define	$$cd$$KN_$$item	9P582000000000011
#define	$$oidnum	2540

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	その他所見
#define	$$cd$$KN_$$item	9P583160800000049
#define	$$item	偶発症の有無
#define	$$cd$$KN_$$item	9P584000000000011
#define	$$oidnum	2010
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P585000000000011
#define	$$oidnum	2550
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P586160800000049
#define	$$item	精密検査による偶発症の有無
#define	$$cd$$KN_$$item	9P587000000000011
#define	$$oidnum	2011
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	肝炎ウイルス検診
#define	$$item	問診肝臓病歴、肝機能が悪いと言われた経験の有無
#define	$$cd$$KN_$$item	9P600000000000011
#define	$$oidnum	2052
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診肝臓病歴、肝機能が悪いと言われた時期
#define	$$cd$$KN_$$item	9P601160800000049
#define	$$item	問診広範な外科的処置歴の有無
#define	$$cd$$KN_$$item	9P602000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診広範な外科的処置時期
#define	$$cd$$KN_$$item	9P603160800000049
#define	$$item	問診妊娠・分娩時の多量出血歴の有無
#define	$$cd$$KN_$$item	9P604000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診妊娠・分娩時の多量出血の時期
#define	$$cd$$KN_$$item	9P605160800000049
#define	$$item	問診定期的な肝機能検査受診の有無
#define	$$cd$$KN_$$item	9P606000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診B型肝炎ウイルス検査の受診歴の有無
#define	$$cd$$KN_$$item	9P607000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診B型肝炎ウイルス検査の受診時期
#define	$$cd$$KN_$$item	9P608160800000049
#define	$$item	問診B型肝炎治療歴の有無
#define	$$cd$$KN_$$item	9P609000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診B型肝炎治療時期
#define	$$cd$$KN_$$item	9P610160800000049
#define	$$item	問診C型肝炎ウイルス検査の受診歴の有無
#define	$$cd$$KN_$$item	9P611000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診C型肝炎ウイルス検査の受診時期
#define	$$cd$$KN_$$item	9P612160800000049
#define	$$item	問診C型肝炎治療歴の有無
#define	$$cd$$KN_$$item	9P613000000000011
#define	$$oidnum	2054
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診C型肝炎治療時期
#define	$$cd$$KN_$$item	9P614160800000049
#define	$$item	B型肝炎ウイルス検査判定
#define	$$cd$$KN_$$item	9P615000000000011
#define	$$oidnum	2640

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	C型肝炎ウイルス検査判定
#define	$$cd$$KN_$$item	9N401000000000011
#define	$$oidnum	2641

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P616000000000011
#define	$$oidnum	2650

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P617160800000049
#define	$$item	問診過去の検査判定
#define	$$cd$$KN_$$item	9P620000000000011
#define	$$oidnum	2052
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診過去の精密検査の対象有無
#define	$$cd$$KN_$$item	9P621000000000011
#define	$$oidnum	2700
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診現在の体重
#define	$$cd$$KN_$$item	9N006000000000001
#define	$$item	問診現在の身長
#define	$$cd$$KN_$$item	9N001000000000001
#define	$$item	問診骨折の既往歴
#define	$$cd$$KN_$$item	9P622000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診過去の骨折の部位
#define	$$cd$$KN_$$item	9P623160800000049
#define	$$item	問診大腿骨近位部骨折の家族歴
#define	$$cd$$KN_$$item	9P624000000000011
#define	$$oidnum	2052
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診喫煙習慣
#define	$$cd$$KN_$$item	9P625000000000011
#define	$$oidnum	2701
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診飲酒量
#define	$$cd$$KN_$$item	9P626000000000001
#define	$$item	問診ステロイド内服
#define	$$cd$$KN_$$item	9P627000000000011
#define	$$oidnum	2702
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診関節リウマチ罹患
#define	$$cd$$KN_$$item	9P628000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診その他の既往歴
#define	$$cd$$KN_$$item	9P629160800000049
#define	$$item	問診活動量（運動頻度）
#define	$$cd$$KN_$$item	9P630000000000011
#define	$$oidnum	2703
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診月経の有無
#define	$$cd$$KN_$$item	9P631000000000011
#define	$$oidnum	2704
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診閉経の理由
#define	$$cd$$KN_$$item	9P632000000000011
#define	$$oidnum	2705
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診閉経年齢
#define	$$cd$$KN_$$item	9P633000000000001
#define	$$item	問診その他問診事項
#define	$$cd$$KN_$$item	9P634160800000049
#define	$$item	DXA検査骨量値
#define	$$cd$$KN_$$item	9Z507195600000001
#define	$$item	DXA検査骨密度
#define	$$cd$$KN_$$item	9Z507195700000001
#define	$$item	DXA検査測定部位
#define	$$cd$$KN_$$item	9Z507195800000049
#define	$$item	DXA検査に使用した機器
#define	$$cd$$KN_$$item	9Z507195900000049
#define	$$item	DXA検査判定
#define	$$cd$$KN_$$item	9Z507000000000011
#define	$$oidnum	2706
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	DXA検査所見
#define	$$cd$$KN_$$item	9Z507160800000049
#define	$$item	エックス線検査骨量値
#define	$$cd$$KN_$$item	9Z531195600000001
#define	$$item	エックス線検査骨密度
#define	$$cd$$KN_$$item	9Z531195700000001
#define	$$item	エックス線検査測定部位
#define	$$cd$$KN_$$item	9Z531195800000049
#define	$$item	エックス線検査に使用した機器
#define	$$cd$$KN_$$item	9Z531195900000049
#define	$$item	エックス線検査判定
#define	$$cd$$KN_$$item	9Z531000000000011
#define	$$oidnum	2706
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	エックス線検査所見
#define	$$cd$$KN_$$item	9Z531160800000049
#define	$$item	CT検査骨量値
#define	$$cd$$KN_$$item	9Z536195600000001
#define	$$item	CT検査骨密度
#define	$$cd$$KN_$$item	9Z536195700000001
#define	$$item	CT検査測定部位
#define	$$cd$$KN_$$item	9Z536195800000049
#define	$$item	CT検査に使用した機器
#define	$$cd$$KN_$$item	9Z536195900000049
#define	$$item	CT検査判定
#define	$$cd$$KN_$$item	9Z536000000000011
#define	$$oidnum	2706
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	CT検査所見
#define	$$cd$$KN_$$item	9Z536160800000049
#define	$$item	超音波検査骨量値
#define	$$cd$$KN_$$item	9Z541195600000001
#define	$$item	超音波検査の結果
#define	$$cd$$KN_$$item	9Z541195700000001
#define	$$item	超音波検査測定部位
#define	$$cd$$KN_$$item	9Z541195800000049
#define	$$item	超音波検査に使用した機器
#define	$$cd$$KN_$$item	9Z541195900000049
#define	$$item	超音波検査判定
#define	$$cd$$KN_$$item	9Z541000000000011
#define	$$oidnum	2706
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	超音波検査所見
#define	$$cd$$KN_$$item	9Z541160800000049
#define	$$item	判定
#define	$$cd$$KN_$$item	9P637000000000011
#define	$$oidnum	2740

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P638000000000011
#define	$$oidnum	2750

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P639160800000049
#define	$$item	問診１日での歯をみがく頻度
#define	$$cd$$KN_$$item	9P650000000000011
#define	$$oidnum	2800
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診歯間ブラシやフロスの使用頻度
#define	$$cd$$KN_$$item	9P651000000000011
#define	$$oidnum	2801
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診過去１年間の歯科検診の受診の有無
#define	$$cd$$KN_$$item	9P652000000000011
#define	$$oidnum	2053
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診喫煙歴
#define	$$cd$$KN_$$item	9P653000000000011
#define	$$oidnum	2802
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診喫煙を開始した年齢
#define	$$cd$$KN_$$item	9P654000000000001
#define	$$item	問診喫煙を止めた年齢
#define	$$cd$$KN_$$item	9P655000000000001
#define	$$item	問診1日の平均喫煙本数
#define	$$cd$$KN_$$item	9P656000000000001
#define	$$item	問診糖尿病罹患の有無
#define	$$cd$$KN_$$item	9P657000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診関節リウマチ罹患の有無
#define	$$cd$$KN_$$item	9P658000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診狭心症・心筋梗塞・脳梗塞罹患の有無
#define	$$cd$$KN_$$item	9P659000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診内蔵脂肪型肥満の有無
#define	$$cd$$KN_$$item	9P660000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診妊娠の有無
#define	$$cd$$KN_$$item	9P661000000000011
#define	$$oidnum	2051
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	問診その他全身の状態
#define	$$cd$$KN_$$item	9P662160800000049
#define	$$item	健全歯数
#define	$$cd$$KN_$$item	9P663000000000001
#define	$$item	未処置歯数
#define	$$cd$$KN_$$item	9P664000000000001
#define	$$item	処置歯数
#define	$$cd$$KN_$$item	9P665000000000001
#define	$$item	喪失歯数
#define	$$cd$$KN_$$item	9P666000000000001
#define	$$item	要補綴歯数
#define	$$cd$$KN_$$item	9P667000000000001
#define	$$item	欠損補綴歯数
#define	$$cd$$KN_$$item	9P668000000000001
#define	$$item	現在歯数
#define	$$cd$$KN_$$item	9P669000000000001
#define	$$item	歯肉出血ＢＯＰ（１７または１６）
#define	$$cd$$KN_$$item	9P670000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯肉出血ＢＯＰ（１１）
#define	$$cd$$KN_$$item	9P671000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯肉出血ＢＯＰ（２６または２７）
#define	$$cd$$KN_$$item	9P672000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯肉出血ＢＯＰ（４７または４６）
#define	$$cd$$KN_$$item	9P673000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯肉出血ＢＯＰ（３１）
#define	$$cd$$KN_$$item	9P674000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯肉出血ＢＯＰ（３６または３７）
#define	$$cd$$KN_$$item	9P675000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯肉出血ＢＯＰ（最大値）
#define	$$cd$$KN_$$item	9P676000000000011
#define	$$oidnum	2803

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（１７または１６）
#define	$$cd$$KN_$$item	9P677000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（１１）
#define	$$cd$$KN_$$item	9P678000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（２６または２７）
#define	$$cd$$KN_$$item	9P679000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（４７または４６）
#define	$$cd$$KN_$$item	9P680000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（３１）
#define	$$cd$$KN_$$item	9P681000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（３６または３７）
#define	$$cd$$KN_$$item	9P682000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯周ポケットＰＤ（最大値）
#define	$$cd$$KN_$$item	9P683000000000011
#define	$$oidnum	2804

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯石の付着
#define	$$cd$$KN_$$item	9P684000000000011
#define	$$oidnum	2805

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	口腔清掃状態
#define	$$cd$$KN_$$item	9P685000000000011
#define	$$oidnum	2806

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	歯列咬合所見
#define	$$cd$$KN_$$item	9P686000000000011
#define	$$oidnum	2050
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	顎関節所見
#define	$$cd$$KN_$$item	9P687000000000011
#define	$$oidnum	2050
#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	粘膜所見
#define	$$cd$$KN_$$item	9P688000000000011
#define	$$oidnum	2050

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	その他所見
#define	$$cd$$KN_$$item	9P689160800000049
#define	$$item	判定区分
#define	$$cd$$KN_$$item	9P690000000000011
#define	$$oidnum	2840

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査結果
#define	$$cd$$KN_$$item	9P691000000000011
#define	$$oidnum	2850

#define	 $$cs$$KN_$$item	$$urn.$$oidnum
#define	$$vs$$KN_$$item	$$url-$$oidnum

#define	$$item	精密検査所見
#define	$$cd$$KN_$$item	9P692160800000049
	
/*
#define	$$cd$$KN_過去の受診歴  9P520000000000011
#define	 $$cd$$KN_過去の受診歴	9P520000000000011
#define	 $$cd$$KN_がんに係る症状の有無	9P521000000000011
#define	 $$cd$$KN_マンモグラフィー検査判定	9N281000000000011
#define	 $$cd$$KN_マンモグラフィー検査所見	9N281160800000049
#define	 $$cd$$KN_精密検査対象有無	9P522000000000011
#define	 $$cd$$KN_その他所見	9P523160800000049
#define	 $$cd$$KN_偶発症の有無	9P524000000000011
#define	 $$cd$$KN_精密検査結果	9P525000000000011
#define	 $$cd$$KN_精密検査所見	9P526160800000049
#define	 $$cd$$KN_精密検査による偶発症の有無	9P527000000000011
*/

// JP_Observation_eMunicipalCheckupG_egg52.incから展開 
* code.coding contains
        obs_$$cd$$KN_過去の受診歴 0..1
    and obs_$$cd$$KN_乳がんに係る症状の有無 0..1
    and obs_$$cd$$KN_喫煙指数 0..1
    and obs_$$cd$$KN_胸部エックス線検査判定 0..1
    and obs_$$cd$$KN_胸部エックス線検査所見 0..1
    and obs_$$cd$$KN_喀痰検査受診日 0..1
    and obs_$$cd$$KN_喀痰検査判定 0..1
    and obs_$$cd$$KN_喀痰検査所見 0..1
    and obs_$$cd$$KN_精密検査対象有無 0..1
    and obs_$$cd$$KN_その他所見 0..1
    and obs_$$cd$$KN_偶発症の有無 0..1
    and obs_$$cd$$KN_精密検査結果 0..1
    and obs_$$cd$$KN_精密検査その他所見 0..1
    and obs_$$cd$$KN_精密検査による偶発症の有無  0..1   

//
* code.coding[obs_$$cd$$KN_過去の受診歴]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_過去の受診歴  (exactly)  //  "$$KN_過去の受診歴"    // 乳がん一次検診,問診,CD,$$urn.2000* code.coding[obs_$$cd$$KN_乳がんに係る症状の有無]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_乳がんに係る症状の有無 (exactly) //   "$$KN_乳がんに係る症状の有無"    // 乳がん一次検診,問診,CD,$$urn.2052* code.coding[obs_$$cd$$KN_喫煙指数]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_喫煙指数  (exactly) //   "$$KN_喫煙指数"    // 乳がん一次検診,問診,PQ,* code.coding[obs_$$cd$$KN_胸部エックス線検査判定]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_胸部エックス線検査判定  (exactly) //   "$$KN_胸部エックス線検査判定"    // 乳がん一次検診,胸部エックス線検査,CD,$$urn.2100* code.coding[obs_$$cd$$KN_胸部エックス線検査所見]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_胸部エックス線検査所見   (exactly) // 乳がん一次検診,胸部エックス線検査,ST,* code.coding[obs_$$cd$$KN_喀痰検査受診日]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_喀痰検査受診日  (exactly) //   "$$KN_喀痰検査受診日"    // 乳がん一次検診,喀痰検査,ST,
* code.coding[obs_$$cd$$KN_喀痰検査判定]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_喀痰検査判定  (exactly) //   "$$KN_喀痰検査判定"    // 乳がん一次検診,喀痰検査,CD,$$urn.2101* code.coding[obs_$$cd$$KN_喀痰検査所見]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_喀痰検査所見  (exactly)  //   "$$KN_喀痰検査所見"    // 乳がん一次検診,喀痰検査,ST,
* code.coding[obs_$$cd$$KN_精密検査対象有無]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_精密検査対象有無  (exactly)  //   "$$KN_精密検査対象有無"    // 乳がん一次検診,検診結果,CD,$$urn.2140* code.coding[obs_$$cd$$KN_その他所見]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_その他所見  (exactly)  //   "$$KN_その他所見"    // 乳がん一次検診,検診結果,ST,
* code.coding[obs_$$cd$$KN_偶発症の有無]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_偶発症の有無  (exactly)     // 乳がん一次検診,検診結果,CD,$$urn.2010* code.coding[obs_$$cd$$KN_精密検査結果]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_精密検査結果  (exactly)  //   "$$KN_精密検査結果"    // 乳がん精密検査,検診結果,CD,$$urn.2150* code.coding[obs_$$cd$$KN_精密検査その他所見]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_精密検査その他所見  (exactly)  //   "$$KN_精密検査その他所見"    // 乳がん精密検査,検診結果,ST,
* code.coding[obs_$$cd$$KN_精密検査による偶発症の有無]
  * system	= $EMCUPX_observation_codes_cs
  * code = #$$cd$$KN_精密検査による偶発症の有無  (exactly)  //   "$$KN_精密検査による偶発症の有無"    // 乳がん精密検査,検診結果,CD,$$urn.2011
//--ここまで
// 検診種別ごとに検診 の結果のvalueSetを検診項目ごとに異なる制約を定義する
//-- ここから
// 乳がん検診
* value[x][valueCodeableConcept].coding contains
        obs_$$cd$$KN_過去の受診歴 0..1
    and obs_$$cd$$KN_乳がんに係る症状の有無 0..1
    and obs_$$cd$$KN_胸部エックス線検査判定 0..1
    and obs_$$cd$$KN_喀痰検査判定 0..1
    and obs_$$cd$$KN_精密検査対象有無 0..1
    and obs_$$cd$$KN_偶発症の有無 0..1
    and obs_$$cd$$KN_精密検査結果 0..1
    and obs_$$cd$$KN_精密検査による偶発症の有無  0..1   * value[x][valueCodeableConcept].coding[obs_$$cd$$KN_過去の受診歴]
  * system	= "$$csys$$KN_過去の受診歴"  (exactly)
  * code from	$$vset$$KN_過去の受診歴 (required)
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_乳がんに係る症状の有無]
  * system	= "$$csys$$KN_乳がんに係る症状の有無" (exactly)
  * code from	$$vset$$KN_乳がんに係る症状の有無 (required) 
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_胸部エックス線検査判定]
  * system	= "$$csys$$KN_胸部エックス線検査判定" (exactly)
  * code from	$$vset$$KN_胸部エックス線検査判定 (required)
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_喀痰検査判定]
  * system	= "$$csys$$KN_喀痰検査判定" (exactly)
  * code from	$$vset$$KN_喀痰検査判定 (required)
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_精密検査対象有無]
  * system	= "$$csys$$KN_精密検査対象有無" (exactly)
  * code from	$$vset$$KN_精密検査対象有無 (required)
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_偶発症の有無]
  * system	= "$$csys$$KN_偶発症の有無" (exactly)
  * code from	$$vset$$KN_偶発症の有無 (required)
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_精密検査結果]
  * system	= "$$csys$$KN_精密検査結果" (exactly)
  * code from	$$vset$$KN_精密検査結果 (required)
* value[x][valueCodeableConcept].coding[obs_$$cd$$KN_精密検査による偶発症の有無]
  * system	= "$$csys$$KN_精密検査による偶発症の有無"  (exactly)
  * code from	$$vset$$KN_精密検査による偶発症の有無 (required)
//-- ここまで
