#define	$$urn   urn:oid:1.2.392.100495.100
#define	$$url   http://jpfhir/eMunicipalCheckup/ValueSet/valueSet

//----
#define	$$KN  骨粗鬆症検診の問診
#define	$$item01	問診過去の検査判定
#define	$$cd01	9P620000000000011
#define	$$oidnum01	2052
#define	$$cs01	$$urn.$$oidnum01
#define	$$vs01	$$url-$$oidnum01


#define	$$item02	問診過去の精密検査の対象有無
#define	$$cd02	9P621000000000011
#define	$$oidnum02	2700
#define	$$cs02	$$urn.$$oidnum02
#define	$$vs02	$$url-$$oidnum02


#define	$$item03	問診現在の体重
#define	$$cd03	9N006000000000001

#define	$$item04	問診現在の身長
#define	$$cd04	9N001000000000001

#define	$$item05	問診骨折の既往歴
#define	$$cd05	9P622000000000011
#define	$$oidnum05	2051
#define	$$cs05	$$urn.$$oidnum05
#define	$$vs05	$$url-$$oidnum05


#define	$$item06	問診過去の骨折の部位
#define	$$cd06	9P623160800000049

#define	$$item07	問診大腿骨近位部骨折の家族歴
#define	$$cd07	9P624000000000011
#define	$$oidnum07	2052
#define	$$cs07	$$urn.$$oidnum07
#define	$$vs07	$$url-$$oidnum07


#define	$$item08	問診喫煙習慣
#define	$$cd08	9P625000000000011
#define	$$oidnum08	2701
#define	$$cs08	$$urn.$$oidnum08
#define	$$vs08	$$url-$$oidnum08


#define	$$item09	問診飲酒量
#define	$$cd09	9P626000000000001

#define	$$item10	問診ステロイド内服
#define	$$cd10	9P627000000000011
#define	$$oidnum10	2702
#define	$$cs10	$$urn.$$oidnum10
#define	$$vs10	$$url-$$oidnum10


#define	$$item11	問診関節リウマチ罹患
#define	$$cd11	9P628000000000011
#define	$$oidnum11	2051
#define	$$cs11	$$urn.$$oidnum11
#define	$$vs11	$$url-$$oidnum11


#define	$$item12	問診その他の既往歴
#define	$$cd12	9P629160800000049

#define	$$item13	問診活動量（運動頻度）
#define	$$cd13	9P630000000000011
#define	$$oidnum13	2703
#define	$$cs13	$$urn.$$oidnum13
#define	$$vs13	$$url-$$oidnum13


#define	$$item14	問診月経の有無
#define	$$cd14	9P631000000000011
#define	$$oidnum14	2704
#define	$$cs14	$$urn.$$oidnum14
#define	$$vs14	$$url-$$oidnum14


#define	$$item15	問診閉経の理由
#define	$$cd15	9P632000000000011
#define	$$oidnum15	2705
#define	$$cs15	$$urn.$$oidnum15
#define	$$vs15	$$url-$$oidnum15


#define	$$item16	問診閉経年齢
#define	$$cd16	9P633000000000001

#define	$$item17	問診その他問診事項
#define	$$cd17	9P634160800000049

#define	$$item18	DXA検査骨量値
#define	$$cd18	9Z507195600000001

#define	$$item19	DXA検査骨密度
#define	$$cd19	9Z507195700000001

#define	$$item20	DXA検査測定部位
#define	$$cd20	9Z507195800000049

#define	$$item21	DXA検査に使用した機器
#define	$$cd21	9Z507195900000049

#define	$$item22	DXA検査判定
#define	$$cd22	9Z507000000000011
#define	$$oidnum22	2706
#define	$$cs22	$$urn.$$oidnum22
#define	$$vs22	$$url-$$oidnum22
#define $$item22   $$item


#define	$$item23	DXA検査所見
#define	$$cd23	9Z507160800000049
#define $$item23   $$item


#define	$$item24	エックス線検査骨量値
#define	$$cd24	9Z531195600000001
#define $$item24   $$item

#define	$$item25	エックス線検査骨密度
#define	$$cd25	9Z531195700000001
#define $$item25   $$item

#define	$$item26	エックス線検査測定部位
#define	$$cd26	9Z531195800000049
#define $$item26   $$item

#define	$$item27	エックス線検査に使用した機器
#define	$$cd27	9Z531195900000049
#define $$item27   $$item

#define	$$item28	エックス線検査判定
#define	$$cd28	9Z531000000000011
#define	$$oidnum28	2706
#define	$$cs28	$$urn.$$oidnum28
#define	$$vs28	$$url-$$oidnum28


#define	$$item29	エックス線検査所見
#define	$$cd29	9Z531160800000049
#define $$item29   $$item


#define	$$item30	CT検査骨量値
#define	$$cd30	9Z536195600000001
#define $$item30   $$item

#define	$$item31	CT検査骨密度
#define	$$cd31	9Z536195700000001
#define $$item31   $$item

#define	$$item32	CT検査測定部位
#define	$$cd32	9Z536195800000049
#define $$item32   $$item

#define	$$item33	CT検査に使用した機器
#define	$$cd33	9Z536195900000049
#define $$item33   $$item

#define	$$item34	CT検査判定
#define	$$cd34	9Z536000000000011
#define	$$oidnum34	2706
#define	$$cs34	$$urn.$$oidnum34
#define	$$vs34	$$url-$$oidnum34


#define	$$item35	CT検査所見
#define	$$cd35	9Z536160800000049
#define $$item35   $$item

#define	$$item36	超音波検査骨量値
#define	$$cd36	9Z541195600000001
#define $$item36   $$item

#define	$$item37	超音波検査の結果
#define	$$cd37	9Z541195700000001
#define $$item37   $$item

#define	$$item38	超音波検査測定部位
#define	$$cd38	9Z541195800000049
#define $$item38   $$item

#define	$$item39	超音波検査に使用した機器
#define	$$cd39	9Z541195900000049
#define $$item39   $$item

#define	$$item40	超音波検査判定
#define	$$cd40	9Z541000000000011
#define	$$oidnum40	2706
#define	$$cs40	$$urn.$$oidnum40
#define	$$vs40	$$url-$$oidnum40


#define	$$item41	超音波検査所見
#define	$$cd41	9Z541160800000049

#define	$$item42	判定
#define	$$cd42	9P637000000000011
#define	$$oidnum42	2740
#define	$$cs42	$$urn.$$oidnum42
#define	$$vs42	$$url-$$oidnum42


#define	$$item43	精密検査結果
#define	$$cd43	9P638000000000011
#define	$$oidnum43	2750
#define	$$cs43	$$urn.$$oidnum43
#define	$$vs43	$$url-$$oidnum43

#define	$$item44	精密検査所見
#define	$$cd44	9P639160800000049
#define $$item44   $$item


//-- ここから
// 骨粗鬆症検診
// JP_Observation_eMunicipalCheckupG_egg57.incから展開 
* code.coding contains
        obs_$$cd01 0..1
    and obs_$$cd02 0..1
    and obs_$$cd03 0..1
    and obs_$$cd04 0..1
    and obs_$$cd05 0..1
    and obs_$$cd06 0..1
    and obs_$$cd07 0..1
    and obs_$$cd08 0..1
    and obs_$$cd09 0..1
    and obs_$$cd10 0..1
    and obs_$$cd11 0..1
    and obs_$$cd12 0..1
    and obs_$$cd13 0..1
    and obs_$$cd14 0..1   
    and obs_$$cd15 0..1
    and obs_$$cd16 0..1
    and obs_$$cd17 0..1
    and obs_$$cd18 0..1
    and obs_$$cd19 0..1
    and obs_$$cd20 0..1
    and obs_$$cd21 0..1
    and obs_$$cd22 0..1
    and obs_$$cd23 0..1
    and obs_$$cd24 0..1   
    and obs_$$cd25 0..1
    and obs_$$cd26 0..1
    and obs_$$cd27 0..1
    and obs_$$cd28 0..1
    and obs_$$cd29 0..1
    and obs_$$cd30 0..1
    and obs_$$cd31 0..1
    and obs_$$cd32 0..1
    and obs_$$cd33 0..1
    and obs_$$cd34 0..1   
    and obs_$$cd35 0..1
    and obs_$$cd36 0..1
    and obs_$$cd37 0..1
    and obs_$$cd38 0..1
    and obs_$$cd39 0..1
    and obs_$$cd40 0..1
    and obs_$$cd41 0..1
    and obs_$$cd42 0..1
    and obs_$$cd43 0..1
    and obs_$$cd44 0..1   
 

//-- ここから 検査項目JLAC10のsystem urlと項目コード（JLAC10)の出力
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd01)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd02)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd03)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd04)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd05)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd06)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd07)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd08)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd09)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd10)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd11)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd12)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd13)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd14)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd15)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd16)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd17)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd18)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd19)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd20)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd21)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd22)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd23)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd24)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd25)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd26)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd27)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd28)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd29)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd30)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd31)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd32)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd33)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd34)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd35)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd36)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd37)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd38)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd39)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd40)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd41)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd42)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd43)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd44)
//--ここまで

//-- ここから
// 骨粗鬆症検診
// 検診種別ごとに検診 の結果のvalueSet へのbindingを検診項目ごとに異なる制約として定義する
/*
* value[x][valueCodeableConcept].coding contains
        obs_$$cd01 0..1
    and obs_$$cd02 0..1
    and obs_$$cd05 0..1
    and obs_$$cd07 0..1
    and obs_$$cd08 0..1
    and obs_$$cd10 0..1
    and obs_$$cd11 0..1
    and obs_$$cd13 0..1
    and obs_$$cd14 0..1
    and obs_$$cd15 0..1
    and obs_$$cd22 0..1
    and obs_$$cd28 0..1
    and obs_$$cd34 0..1
    and obs_$$cd40 0..1
    and obs_$$cd42 0..1
    and obs_$$cd43 0..1


* insert valCC_coding_slicing($$cd01, $$cs01, $$vs01)
* insert valCC_coding_slicing($$cd02, $$cs02, $$vs02)
* insert valCC_coding_slicing($$cd05, $$cs05, $$vs05)
* insert valCC_coding_slicing($$cd07, $$cs07, $$vs07)
* insert valCC_coding_slicing($$cd08, $$cs08, $$vs08)
* insert valCC_coding_slicing($$cd10, $$cs10, $$vs10)
* insert valCC_coding_slicing($$cd11, $$cs11, $$vs11)
* insert valCC_coding_slicing($$cd13, $$cs13, $$vs13)
* insert valCC_coding_slicing($$cd14, $$cs14, $$vs14)
* insert valCC_coding_slicing($$cd15, $$cs15, $$vs15)
* insert valCC_coding_slicing($$cd22, $$cs22, $$vs22)
* insert valCC_coding_slicing($$cd28, $$cs28, $$vs28)
* insert valCC_coding_slicing($$cd34, $$cs34, $$vs34)
* insert valCC_coding_slicing($$cd40, $$cs40, $$vs40)
* insert valCC_coding_slicing($$cd42, $$cs42, $$vs42)
* insert valCC_coding_slicing($$cd43, $$cs43, $$vs43)
*/
//-- ここまで
