#define	$$urn   urn:oid:1.2.392.100495.100
#define	$$url   http://jpfhir/eMunicipalCheckup/ValueSet/valueSet

//----------
#define $$KN  肺がん検診

#define	$$item01	過去の受診歴
#define	$$oidnum01	2000
#define $$cd01 9P500000000000011
#define	$$cs01 $$urn.$$oidnum01
#define	$$vs01 $$url-$$oidnum01

#define	$$item02	がんに係る症状の有無
#define	$$oidnum02	2052
#define $$cd02	9P501000000000011
#define	$$cs02	$$urn.$$oidnum02
#define	$$vs02	$$url-$$oidnum02


#define	$$item03	喫煙指数
#define $$cd03	9N737000000000012


#define	$$item04	胸部エックス線検査判定
#define	$$oidnum04	2100
#define $$cd04	9P502000000000011
#define	$$cs04	$$urn.$$oidnum04
#define	$$vs04	$$url-$$oidnum04


#define	$$item05	胸部エックス線検査判定
#define $$cd05	9P503160800000049


#define	$$item06	喀痰検査受診日
#define $$cd06	7A030161506144349


#define	$$item07	喀痰検査判定
#define	$$oidnum07	2101
#define $$cd07	7A030000006144311
#define	$$cs07	$$urn.$$oidnum09
#define	$$vs07	$$url-$$oidnum09


#define	$$item08	喀痰検査所見
#define $$cd08 7A030160806144349


#define	$$item09	精密検査対象有無
#define	$$oidnum09	2140
#define $$cd09	9P504000000000011
#define	$$cs09	$$urn.$$oidnum10
#define	$$vs09	$$url-$$oidnum10


#define	$$item10	その他所見
#define $$cd10	9P505160800000049


#define	$$item11	偶発症の有無
#define	$$oidnum11	2010
#define $$cd11	9P506000000000011
#define	$$cs11	$$urn.$$oidnum11
#define	$$vs11	$$url-$$oidnum11


#define	$$item12	精密検査結果
#define	$$oidnum12	2150
#define $$cd12	9P507000000000011
#define	$$cs12	$$urn.$$oidnum12
#define	$$vs12	$$url-$$oidnum12


#define	$$item13	精密検査その他所見
#define $$cd13	9P508160800000049


#define	$$item14	精密検査による偶発症の有無
#define	$$oidnum14	2011
#define $$cd14	9P509000000000011
#define	$$cs14	$$urn.$$oidnum14
#define	$$vs14	$$url-$$oidnum14
