#define	$$urn   urn:oid:1.2.392.100495.100
#define	$$url   http://jpfhir/eMunicipalCheckup/ValueSet/valueSet

//----歯周疾患検診
#define	$$KN  歯周疾患検診

#define	$$item01	問診１日での歯をみがく頻度
#define	$$cd01	9P650000000000011
#define	$$oidnum01	2800
#define	$$cs01	$$urn.$$oidnum01
#define	$$vs01	$$url-$$oidnum01


#define	$$item02	問診歯間ブラシやフロスの使用頻度
#define	$$cd02	9P651000000000011
#define	$$oidnum02	2801
#define	$$cs02	$$urn.$$oidnum02
#define	$$vs02	$$url-$$oidnum02


#define	$$item03	問診過去１年間の歯科検診の受診の有無
#define	$$cd03	9P652000000000011
#define	$$oidnum03	2053
#define	$$cs03	$$urn.$$oidnum03
#define	$$vs03	$$url-$$oidnum03


#define	$$item04	問診喫煙歴
#define	$$cd04	9P653000000000011
#define	$$oidnum04	2802
#define	$$cs04	$$urn.$$oidnum04
#define	$$vs04	$$url-$$oidnum04


#define	$$item05	問診喫煙を開始した年齢
#define	$$cd05	9P654000000000001
#define $$item05   $$item

#define	$$item06	問診喫煙を止めた年齢
#define	$$cd06	9P655000000000001
#define $$item06   $$item

#define	$$item07	問診1日の平均喫煙本数
#define	$$cd07	9P656000000000001
#define $$item07   $$item

#define	$$item08	問診糖尿病罹患の有無
#define	$$cd08	9P657000000000011
#define	$$oidnum08	2051
#define	$$cs08	$$urn.$$oidnum08
#define	$$vs08	$$url-$$oidnum08


#define	$$item09	問診関節リウマチ罹患の有無
#define	$$cd09	9P658000000000011
#define	$$oidnum09	2051
#define	$$cs09	$$urn.$$oidnum09
#define	$$vs09	$$url-$$oidnum09


#define	$$item10	問診狭心症・心筋梗塞・脳梗塞罹患の有無
#define	$$cd10	9P659000000000011
#define	$$oidnum10	2051
#define	$$cs10	$$urn.$$oidnum10
#define	$$vs10	$$url-$$oidnum10


#define	$$item11	問診内蔵脂肪型肥満の有無
#define	$$cd11	9P660000000000011
#define	$$oidnum11	2051
#define	$$cs11	$$urn.$$oidnum11
#define	$$vs11	$$url-$$oidnum11


#define	$$item12	問診妊娠の有無
#define	$$cd12	9P661000000000011
#define	$$oidnum12	2051
#define	$$cs12	$$urn.$$oidnum12
#define	$$vs12	$$url-$$oidnum12


#define	$$item13	問診その他全身の状態
#define	$$cd13	9P662160800000049

#define	$$item14	健全歯数
#define	$$cd14	9P663000000000001

#define	$$item15	未処置歯数
#define	$$cd15	9P664000000000001

#define	$$item16	処置歯数
#define	$$cd16	9P665000000000001

#define	$$item17	喪失歯数
#define	$$cd17	9P666000000000001

#define	$$item18	要補綴歯数
#define	$$cd18	9P667000000000001

#define	$$item19	欠損補綴歯数
#define	$$cd19	9P668000000000001

#define	$$item20	現在歯数
#define	$$cd20	9P669000000000001

#define	$$item21	歯肉出血ＢＯＰ（１７または１６）
#define	$$cd21	9P670000000000011
#define	$$oidnum21	2803
#define	$$cs21	$$urn.$$oidnum21
#define	$$vs21	$$url-$$oidnum21


#define	$$item22	歯肉出血ＢＯＰ（１１）
#define	$$cd22	9P671000000000011
#define	$$oidnum22	2803
#define	$$cs22	$$urn.$$oidnum22
#define	$$vs22	$$url-$$oidnum22


#define	$$item23	歯肉出血ＢＯＰ（２６または２７）
#define	$$cd23	9P672000000000011
#define	$$oidnum23	2803
#define	$$cs23	$$urn.$$oidnum23
#define	$$vs23	$$url-$$oidnum23


#define	$$item24	歯肉出血ＢＯＰ（４７または４６）
#define	$$cd24	9P673000000000011
#define	$$oidnum24	2803
#define	$$cs24	$$urn.$$oidnum24
#define	$$vs24	$$url-$$oidnum24


#define	$$item25	歯肉出血ＢＯＰ（３１）
#define	$$cd25	9P674000000000011
#define	$$oidnum25	2803
#define	$$cs25	$$urn.$$oidnum25
#define	$$vs25	$$url-$$oidnum25


#define	$$item26	歯肉出血ＢＯＰ（３６または３７）
#define	$$cd26	9P675000000000011
#define	$$oidnum26	2803
#define	$$cs26	$$urn.$$oidnum26
#define	$$vs26	$$url-$$oidnum26


#define	$$item27	歯肉出血ＢＯＰ（最大値）
#define	$$cd27	9P676000000000011
#define	$$oidnum27	2803
#define	$$cs27	$$urn.$$oidnum27
#define	$$vs27	$$url-$$oidnum27


#define	$$item28	歯周ポケットＰＤ（１７または１６）
#define	$$cd28	9P677000000000011
#define	$$oidnum28	2804
#define	$$cs28	$$urn.$$oidnum28
#define	$$vs28	$$url-$$oidnum28


#define	$$item29	歯周ポケットＰＤ（１１）
#define	$$cd29	9P678000000000011
#define	$$oidnum29	2804
#define	$$cs29	$$urn.$$oidnum29
#define	$$vs29	$$url-$$oidnum29


#define	$$item30	歯周ポケットＰＤ（２６または２７）
#define	$$cd30	9P679000000000011
#define	$$oidnum30	2804
#define	$$cs30	$$urn.$$oidnum30
#define	$$vs30	$$url-$$oidnum30


#define	$$item31	歯周ポケットＰＤ（４７または４６）
#define	$$cd31	9P680000000000011
#define	$$oidnum31	2804
#define	$$cs31	$$urn.$$oidnum31
#define	$$vs31	$$url-$$oidnum31


#define	$$item32	歯周ポケットＰＤ（３１）
#define	$$cd32	9P681000000000011
#define	$$oidnum32	2804
#define	$$cs32	$$urn.$$oidnum32
#define	$$vs32	$$url-$$oidnum32


#define	$$item33	歯周ポケットＰＤ（３６または３７）
#define	$$cd33	9P682000000000011
#define	$$oidnum33	2804
#define	$$cs33	$$urn.$$oidnum33
#define	$$vs33	$$url-$$oidnum33


#define	$$item34	歯周ポケットＰＤ（最大値）
#define	$$cd34	9P683000000000011
#define	$$oidnum34	2804
#define	$$cs34	$$urn.$$oidnum34
#define	$$vs34	$$url-$$oidnum34


#define	$$item35	歯石の付着
#define	$$cd35	9P684000000000011
#define	$$oidnum35	2805
#define	$$cs35	$$urn.$$oidnum35
#define	$$vs35	$$url-$$oidnum35


#define	$$item36	口腔清掃状態
#define	$$cd36	9P685000000000011
#define	$$oidnum36	2806
#define	$$cs36	$$urn.$$oidnum36
#define	$$vs36	$$url-$$oidnum36


#define	$$item37	歯列咬合所見
#define	$$cd37	9P686000000000011
#define	$$oidnum37	2050
#define	$$cs37	$$urn.$$oidnum37
#define	$$vs37	$$url-$$oidnum37


#define	$$item38	顎関節所見
#define	$$cd38	9P687000000000011
#define	$$oidnum38	2050
#define	$$cs38	$$urn.$$oidnum38
#define	$$vs38	$$url-$$oidnum38


#define	$$item39	粘膜所見
#define	$$cd39	9P688000000000011
#define	$$oidnum39	2050
#define	$$cs39	$$urn.$$oidnum39
#define	$$vs39	$$url-$$oidnum39


#define	$$item40	その他所見
#define	$$cd40	9P689160800000049

#define	$$item41	判定区分
#define	$$cd41	9P690000000000011
#define	$$oidnum41	2840
#define	$$cs41	$$urn.$$oidnum41
#define	$$vs41	$$url-$$oidnum41


#define	$$item42	精密検査結果
#define	$$cd42	9P691000000000011
#define	$$oidnum42	2850
#define	$$cs42	$$urn.$$oidnum42
#define	$$vs42	$$url-$$oidnum42

#define	$$item43	精密検査所見
#define	$$cd43	9P692160800000049

//-- ここから
//  歯周疾患検診
// JP_Observation_eMunicipalCheckupG_egg58.incから展開 
* code.coding contains
        obs_$$cd01 0..1
    and obs_$$cd02 0..1
    and obs_$$cd03 0..1
    and obs_$$cd04 0..1
    and obs_$$cd05 0..1
    and obs_$$cd06 0..1
    and obs_$$cd07 0..1
    and obs_$$cd08 0..1
    and obs_$$cd09 0..1
    and obs_$$cd10 0..1
    and obs_$$cd11 0..1
    and obs_$$cd12 0..1
    and obs_$$cd13 0..1
    and obs_$$cd14 0..1   
    and obs_$$cd15 0..1
    and obs_$$cd16 0..1
    and obs_$$cd17 0..1
    and obs_$$cd18 0..1
    and obs_$$cd19 0..1
    and obs_$$cd20 0..1
    and obs_$$cd21 0..1
    and obs_$$cd22 0..1
    and obs_$$cd23 0..1
    and obs_$$cd24 0..1   
    and obs_$$cd25 0..1
    and obs_$$cd26 0..1
    and obs_$$cd27 0..1
    and obs_$$cd28 0..1
    and obs_$$cd29 0..1
    and obs_$$cd30 0..1
    and obs_$$cd31 0..1
    and obs_$$cd32 0..1
    and obs_$$cd33 0..1
    and obs_$$cd34 0..1   
    and obs_$$cd35 0..1
    and obs_$$cd36 0..1
    and obs_$$cd37 0..1
    and obs_$$cd38 0..1
    and obs_$$cd39 0..1
    and obs_$$cd40 0..1
    and obs_$$cd41 0..1
    and obs_$$cd42 0..1
    and obs_$$cd43 0..1
 

//-- ここから 検査項目JLAC10のsystem urlと項目コード（JLAC10)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd01)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd02)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd03)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd04)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd05)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd06)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd07)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd08)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd09)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd10)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd11)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd12)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd13)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd14)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd15)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd16)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd17)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd18)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd19)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd20)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd21)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd22)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd23)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd24)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd25)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd26)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd27)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd28)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd29)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd30)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd31)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd32)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd33)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd34)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd35)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd36)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd37)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd38)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd39)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd40)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd41)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd42)
* insert Obs_code_coding_slicing($$EMCUPX_observation_codes_cs, $$cd43)
//--ここまで

//-- ここから
//  歯周疾患検診
// 検診種別ごとに検診 の結果のvalueSet へのbindingを検診項目ごとに異なる制約として定義する
/*
* value[x][valueCodeableConcept].coding contains
        obs_$$cd01 0..1
    and obs_$$cd02 0..1
    and obs_$$cd03 0..1
    and obs_$$cd04 0..1
    and obs_$$cd08 0..1
    and obs_$$cd09 0..1
    and obs_$$cd10 0..1
    and obs_$$cd11 0..1
    and obs_$$cd12 0..1
    and obs_$$cd21 0..1
    and obs_$$cd22 0..1
    and obs_$$cd23 0..1
    and obs_$$cd25 0..1
    and obs_$$cd26 0..1
    and obs_$$cd27 0..1
    and obs_$$cd28 0..1  
    and obs_$$cd29 0..1
    and obs_$$cd30 0..1
    and obs_$$cd31 0..1
    and obs_$$cd32 0..1
    and obs_$$cd33 0..1
    and obs_$$cd34 0..1
    and obs_$$cd35 0..1
    and obs_$$cd36 0..1  
    and obs_$$cd37 0..1
    and obs_$$cd38 0..1
    and obs_$$cd39 0..1  

* insert valCC_coding_slicing($$cd01, $$cs01,  $$vs01)
* insert valCC_coding_slicing($$cd02, $$cs02,  $$vs02)
* insert valCC_coding_slicing($$cd03, $$cs03,  $$vs03)
* insert valCC_coding_slicing($$cd04, $$cs04,  $$vs04)
* insert valCC_coding_slicing($$cd08, $$cs08,  $$vs08)
* insert valCC_coding_slicing($$cd09, $$cs09,  $$vs09)
* insert valCC_coding_slicing($$cd10, $$cs10,  $$vs10)
* insert valCC_coding_slicing($$cd11, $$cs11,  $$vs11)
* insert valCC_coding_slicing($$cd12, $$cs12,  $$vs12)
* insert valCC_coding_slicing($$cd21, $$cs21,  $$vs21)
* insert valCC_coding_slicing($$cd22, $$cs22,  $$vs22)
* insert valCC_coding_slicing($$cd23, $$cs23,  $$vs23)
* insert valCC_coding_slicing($$cd25, $$cs25,  $$vs25)
* insert valCC_coding_slicing($$cd26, $$cs26,  $$vs26)
* insert valCC_coding_slicing($$cd27, $$cs27,  $$vs27)
* insert valCC_coding_slicing($$cd28, $$cs28,  $$vs28)  
* insert valCC_coding_slicing($$cd29, $$cs29,  $$vs29)
* insert valCC_coding_slicing($$cd30, $$cs30,  $$vs30)
* insert valCC_coding_slicing($$cd31, $$cs31,  $$vs31)
* insert valCC_coding_slicing($$cd32, $$cs32,  $$vs32)
* insert valCC_coding_slicing($$cd33, $$cs33,  $$vs33)
* insert valCC_coding_slicing($$cd34, $$cs34,  $$vs34)
* insert valCC_coding_slicing($$cd35, $$cs35,  $$vs35)
* insert valCC_coding_slicing($$cd36, $$cs36,  $$vs36)  
* insert valCC_coding_slicing($$cd37, $$cs37,  $$vs37)
* insert valCC_coding_slicing($$cd38, $$cs38,  $$vs38)
* insert valCC_coding_slicing($$cd39, $$cs39,  $$vs39)  
*/
//-- ここまで
